version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: 4network-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: 4network
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
